import { House } from '@model/house';
import { Owner } from '@model/owner';
import { Rental } from '@model/rental';
import { Funding } from '@model/funding';
import { Provider } from '@model/provider';
import { HouseCo } from './syndic/house-co';
import { HomeCo } from './syndic/home-co';
import { Ticket } from './ticket';
export interface Construction {
  uuid?: any;
  id?: any;
  code?: string;
  nom?: string;
  description?: string;
  type?: string;
  etat?: string;
  montant?: number;
  pourcentage?: number;
  searchableTitle?: string;
  budget?: number;
  date?: string;
  dateD?: string;
  dateF?: string;
  house?: House;
  rental?: Rental;
  trustee?: any;
  houseCo?: HouseCo;
  homeCo?: HomeCo;
  infrastructure: any;
  nature?: any;
  owner?: Owner;
  optionProductions?: any[];
  provider?: Provider;
  funding?: Funding;
  ticket?: Ticket;
  production?: any;
  telephone?: string;
  photoSrc?: string;
  createdAt?: string;
  updatedAt?: string;
  createdAtAt?: string;
  updatedAtAt?: string;
  create?: string;
  update?: string;
}
