import { Rental } from '@model/rental';
import { Mandate } from '@model/mandate';
import { Owner } from '@model/owner';
import { Folder } from '@model/folder';
import { Repayment } from '@model/repayment';
import { FolderFiles } from '@model/folder-files';

export interface House {
  uuid?: any;
  id?: any;
  code?: string;
  agency_id?: any;
  owner_id?: any;
  nom?: string;
  autreType?: string;
  mandate?: Mandate;
  photoSrc?: string;
  owner?: Owner;
  attribuates?: any[];
  blockHouses?: any[];
  folderCustomer?: Folder;
  nbrLocative?: number;
  nbrLocativeO?: number;
  nbrLocativeD?: number;
  nbrLocativeR?: number;
  loyer?: number;
  charge?: number;
  marketBlocks?:any
  valeurLocativeO?: number;
  valeurLocativeD?: number;
  valeurLocativeR?: number;
  numerotation?: number;
  etat?: string;
  domaine?: string;
  resilie?: boolean;
  titre?: boolean;
  isMandat?: boolean;
  isDelete?: boolean;
  numTitre?: string;
  optionTitre?: string;
  bornage?: boolean;
  viabilisation?: boolean;
  village?: string;
  approuve?: boolean;
  numApprobation?: string;
  dateApprobation?: any;
  nbrPiece?: number;
  nbrParking?: number;
  salleEau?: number;
  nbrNiveau?: number;
  jardin?: boolean;
  piscine?: boolean;
  photoUuid?: string;
  folderUuid?: string;
  photo?: string;
  folder?: FolderFiles;
  valeur?: number;
  montantV?: number;
  type?: string;
  disponible?: string;
  ville?: string;
  commune?: string;
  quartier?: string;
  lng?: number;
  lat?: number;
  lot?: string;
  ilot?: string;
  superfice?: number;
  angle?: boolean;
  presEau?: boolean;
  piedsEau?: boolean;
  bordureVoie?: boolean;
  terreFerme?: boolean;
  basFond?: boolean;
  ecole?: boolean;
  marche?: boolean;
  distanceEau?: number;
  distanceRoute?: number;
  hauteur?: number;
  altitude?: number;
  rentals?: Rental[];
  repayments?: Repayment[];
  options?: [null];
  createdAt?: string;
  updatedAt?: string;
  create?: string;
  update?: string;
  searchableTitle?: string;
  searchableDetail?: string;
  numSodeci?: string;
  numCie?: string;
  typeBien?: any;
}
